# -*- coding: utf-8 -*-
"""Spotify User Behavior And Pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T1NGFG_QGueAWGyEaWN-p2sX8SnAns-m

# **LogisiticRegression**

#Step 1: Import Required Libraries
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""#Step 2: Load Dataset"""

data = pd.read_csv("spotify_user_behavior_realistic_50000_rows.csv")

"""#Step 3: View Dataset"""

data.head()

"""#Step 4: Prepare Features (X) and Target (y)"""

X = data[['country','age','subscription_type','ad_interaction',
          'music_suggestion_rating_1_to_5','avg_listening_hours_per_week',
          'favorite_genre','primary_device']]


X = pd.get_dummies(X, drop_first=True)

y = data['inactive_3_months_flag']

X.shape

y=data[['inactive_3_months_flag']]

y.shape

"""#Step 5: Split Dataset"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state =0)

X_train.shape

X_test.shape

y_train.shape

y_test.shape

"""#Step 6: Train Model"""

LR = LogisticRegression()
LR.fit(X_train, y_train)

"""#Step 7: Make Predictions"""

y_pre = LR.predict(X_test)

accuracy = accuracy_score(y_test, y_pre)
print("Accuracy:", accuracy)

"""# **DecisionTreeClassifier**

#Step 1: Import Required Libraries
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

"""#Step 2: Load Dataset"""

data = pd.read_csv("spotify_user_behavior_realistic_50000_rows.csv")

"""#Step 3: View Dataset"""

data.head()

"""#Step 4: Prepare Features (X) and Target (y)"""

X = data[['country','age','subscription_type','ad_interaction',
          'music_suggestion_rating_1_to_5','avg_listening_hours_per_week',
          'favorite_genre','primary_device']]


X = pd.get_dummies(X, drop_first=True)

y = data['inactive_3_months_flag']

X.shape

y=data[['inactive_3_months_flag']]

y.shape

"""#Step 5: Split Dataset"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state =0)

X_train.shape

X_test.shape

y_train.shape

y_test.shape

"""#Step 6: Train Model"""

DT = DecisionTreeClassifier()
DT.fit(X_train, y_train)

y_pre=DT.predict(X_test)

accuracy=accuracy_score(y_test, y_pre)
print("Accuracy:", accuracy)

"""from the above data we can conclude that the Decision Tree Classifier is better.

Because its accuracy is consistently higher than Logistic Regression for all test sizes.
"""

